### ISSUE TITLE
my result of hector_slam is not same with your result

### ISSUE THREAD

**Issue by stmoon** [tu-darmstadt-ros-pkg/hector_slam#6]
Hello.

I'm interested with your project. so I try to test by same bag data (Team_Hector_MappingBox_RoboCup_2011_Rescue_Arena.bag).

However, it is not same with your result.
I just used your source code ( catkin branch). and I refer to your tutorial (hector_slam/Tutorials/MappingUsingLoggedData, http://wiki.ros.org/hector_slam/Tutorials/MappingUsingLoggedData)

please advise me the reason why the result is not same.

Thank you in advance

Best Regards,
stmoon

![result](https://f.cloud.github.com/assets/3262128/1819463/ca41b40e-7095-11e3-9075-bbd0a670c514.png)
![Uploading result.png . . .]()

**Comment by skohlbr** [comment]
It appears this issue is caused by catkin_make defaulting to building in Debug mode (see also http://answers.ros.org/question/71965/catkin-compiled-code-runs-3x-slower/). When I first tried it, I had 104% CPU consumption. After compiling with

<pre>
catkin_make -DCMAKE_BUILD_TYPE=Release
</pre>

CPU consumption drops to about 8% on average and the map looks as expected.

**Comment by stmoon** [comment]
Thank you very much!!!
It works well...

**Comment by lukelu0520** [comment]
Dear hector slam friends, 

Even compiled/built using catkin_make -DCMAKE_BUILD_TYPE=Release, we still get different result(s). In fact, got many different results (each time is different) by simply follow the tutorial: http://wiki.ros.org/hector_slam/Tutorials/MappingUsingLoggedData

Maybe we miss something. We notice that results are quite aligned in the first ~30 seconds, but goes chaotic along the time. Does rosbag play have chaotic effect ? Hope to hear your expertise.
