### ISSUE TITLE
Noetic release

### ISSUE THREAD

**Issue by mintar** [tu-darmstadt-ros-pkg/hector_slam#76]
Could you release hector_slam into ROS Noetic, please?

**Comment by StefanFabian** [comment]
We probably will once we've started making the switch which will not happen before moveit and other major packages are officially released.

**Comment by mintar** [comment]
Thanks for the quick response! This is not super urgent for me, I can be patient. :)

**Comment by Timple** [comment]
I guess most major packages are officially released now :slightly_smiling_face:

**Comment by StefanFabian** [comment]
True, however, with the switch to noetic, I've also taken the time to port `hector_geotiff` from Qt4 to Qt5 which was quite a bit harder than it sounds.
Could use a bit more testing and I also vaguely remember there being a cyclic dependency issue I wanted to fix before releasing on noetic.

**Comment by StefanFabian** [comment]
@mintar @Timple and anyone who is interested.
I have pushed a clean up commit on noetic-devel.
If you guys could confirm that whatever you're using hector_slam for still works, I will prepare a noetic release.
The biggest change is that the launch files from `hector_geotiff` were moved to `hector_geotiff_launch` because they depend on `hector_geotiff_plugins`.

**Comment by mintar** [comment]
I've tested my use case ([hector_mapping on the MiR robot](https://github.com/dfki-ric/mir_robot#gazebo-demo-mapping)) and can confirm that it works on noetic. I only use the `hector_mapping` part, so I haven't tested any of the other stuff, like `hector_geotiff`.

**Comment by StefanFabian** [comment]
Alright, I've just made a release. Could take a while until it's synced, though.
